[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]

[workspace.package]
version = "0.1.0"
authors = ["Celeste Pel√°ez <celeste@etheryal.net>"]
edition = "2024"
license = "MIT or Apache-2.0"
readme = "./README.md"
