[package]
name = "sterling-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
